# Generated by Django 3.2.7 on 2021-09-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Acer', 'Acer'), ('Asus', 'Asus'), ('HP', 'HP'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Sony', 'Sony'), ('Samsung', 'Samsung'), ('Toshiba', 'Toshiba'), ('Compaq', 'Compaq'), ('Walton', 'Walton'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(choices=[('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Barishal', 'Barishal'), ('Comilla', 'Comilla'), ('Rangpur', 'Rangpur'), ('Gazipur', 'Gazipur'), ('Narayanganj', 'Narayanganj')], max_length=100),
        ),
    ]
